// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGgPqn5TCSWb_G0pF8RnZaWExuS7gR1lQ',
    appId: '1:632069230331:web:f90beac28d4350b2afaa5e',
    messagingSenderId: '632069230331',
    projectId: 'contact-demo-23',
    authDomain: 'contact-demo-23.firebaseapp.com',
    storageBucket: 'contact-demo-23.appspot.com',
    measurementId: 'G-YFYGTBQ0FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSYYApGXalwigXryxP_YcMpENG_5OaBbQ',
    appId: '1:632069230331:android:61c3ce392b1236cfafaa5e',
    messagingSenderId: '632069230331',
    projectId: 'contact-demo-23',
    storageBucket: 'contact-demo-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-8P6V3UlxCI1JtXdOm_QpVkxqTUumIYM',
    appId: '1:632069230331:ios:75b7a7adfbbf5badafaa5e',
    messagingSenderId: '632069230331',
    projectId: 'contact-demo-23',
    storageBucket: 'contact-demo-23.appspot.com',
    androidClientId: '632069230331-iaebpgrett5s82ae6pb0s63lfj8qkiil.apps.googleusercontent.com',
    iosClientId: '632069230331-t6upgv2dikig75pg1k71nof7bi6tivlf.apps.googleusercontent.com',
    iosBundleId: 'com.startapp.contactDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-8P6V3UlxCI1JtXdOm_QpVkxqTUumIYM',
    appId: '1:632069230331:ios:039a48936846aaf5afaa5e',
    messagingSenderId: '632069230331',
    projectId: 'contact-demo-23',
    storageBucket: 'contact-demo-23.appspot.com',
    androidClientId: '632069230331-iaebpgrett5s82ae6pb0s63lfj8qkiil.apps.googleusercontent.com',
    iosClientId: '632069230331-vkfsn2qvajnagd5ehj321ldp2mrjq4hp.apps.googleusercontent.com',
    iosBundleId: 'com.startapp.contactDemo.RunnerTests',
  );
}
